apiVersion: batch/v1
kind: Job
metadata:
  name: myapp
spec:
  template:
    spec:
      containers:
      - name: demo
        image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/prp
        command:
        - "python"
        args:
        - "/opt/repo/nrp-examples/hello_world.py"
        - "nrp-batch-job"
        volumeMounts:
        - name: git-repo
          mountPath: /opt/repo
        resources:
          limits:
            memory: 1Gi
            cpu: "1"
          requests:
            memory: 1Gi
            cpu: "1"
      initContainers:
      - name: init-clone-repo
        image: alpine/git
        args:
          - clone
          - --single-branch
          - https://github.com/boettiger-lab/nrp-examples.git
          - /opt/repo/nrp-examples
        volumeMounts:
          - name: git-repo
            mountPath: /opt/repo
        resources:
          limits:
            memory: 1Gi
            cpu: "1"
          requests:
            memory: 1Gi
            cpu: "1"
      volumes:
      - name: git-repo
        emptyDir: {}
      restartPolicy: Never
  backoffLimit: 5


